import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const docsDir = path.join(__dirname, '../docs');

// Regex patterns for markdown links - only match proper markdown syntax [text](url)
// NOT angle bracket links like <https://...> or <placeholder>
const linkPatterns = [
  /\[([^\]\n]+)\]\(([^)\n]+)\)/g, // [text](url) - proper markdown links only // NOSONAR
];

function getAllMarkdownFiles(dir) {
  let files = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files = files.concat(getAllMarkdownFiles(fullPath));
    } else if (entry.name.endsWith('.md') || entry.name.endsWith('.mdx')) {
      files.push(fullPath);
    }
  }

  return files;
}

function resolveLink(link, fromFile) {
  // Skip external URLs, anchors only, and special schemes
  if (link.startsWith('http://') || link.startsWith('https://') || link.startsWith('mailto:') || link.startsWith('javascript:') || link.startsWith('#')) {
    return null;
  }

  // Skip placeholder-style links with angle brackets
  if (link.includes('<') || link.includes('>')) {
    return null;
  }

  // Remove hash/anchor
  const [pathname] = link.split('#');

  if (!pathname) {
    return null; // anchor-only link
  }

  let targetPath;
  if (pathname.startsWith('/')) {
    // Absolute path
    if (pathname.startsWith('/docs/')) {
      // /docs/category/* are auto-generated by Docusaurus, skip checking
      if (pathname.startsWith('/docs/category/')) {
        return null;
      }

      // /docs/wiki/*, /docs/development/*, /docs/sponsors/* etc
      // Remove the leading '/docs/' and resolve in docs dir
      targetPath = path.join(docsDir, pathname.slice(6));
    } else if (pathname.match(/^\/(?:img|resources|reference|data|sitl)\//)) {
      // Static assets - these live in static/ directory, not docs/
      // Skip checking static assets (they're in a different directory)
      return null;
    } else {
      // Other absolute paths - resolve from docs root
      targetPath = path.join(docsDir, pathname.slice(1));
    }
  } else {
    // Relative path
    const fromDir = path.dirname(fromFile);
    targetPath = path.normalize(path.join(fromDir, pathname));
  }

  return targetPath;
}

function linkExists(targetPath) {
  // Try the path as-is
  if (fs.existsSync(targetPath)) {
    return true;
  }

  // Try with .md extension (Docusaurus strips .md from links)
  if (fs.existsSync(targetPath + '.md')) {
    return true;
  }

  // Try with .mdx extension
  if (fs.existsSync(targetPath + '.mdx')) {
    return true;
  }

  // Try as directory with index.mdx
  if (fs.existsSync(path.join(targetPath, 'index.mdx'))) {
    return true;
  }

  // Try as directory with index.md
  if (fs.existsSync(path.join(targetPath, 'index.md'))) {
    return true;
  }

  return false;
}

function checkFile(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const lines = content.split('\n');
  const errors = [];

  lines.forEach((line, lineIndex) => {
    let match;
    while ((match = linkPatterns[0].exec(line)) !== null) {
      // Strip optional inline title (e.g. 'title' or "title" after the URL)
      const linkUrl = match[2].replace(/\s+(?:"[^"]*"|'[^']*')\s*$/, '').trim() // NOSONAR
      // Strip query string before resolving (e.g. ?fbclid=...)
      const linkUrlNoQuery = linkUrl.split('?')[0];
      // URL-decode so %20 etc. resolve to actual filenames
      const linkUrlDecoded = decodeURIComponent(linkUrlNoQuery);

      const resolvedPath = resolveLink(linkUrlDecoded, filePath);
      if (resolvedPath && !linkExists(resolvedPath)) {
        errors.push({
          file: filePath,
          line: lineIndex + 1,
          link: linkUrl,
          reason: `File not found: ${resolvedPath}`,
        })
      }
    }
  });

  return errors;
}

function main() {
  if (!fs.existsSync(docsDir)) {
    console.error(`Docs directory not found: ${docsDir}`);
    process.exit(1);
  }

  const files = getAllMarkdownFiles(docsDir);
  const allErrors = [];

  for (const file of files) {
    const errors = checkFile(file);
    allErrors.push(...errors);
  }

  if (allErrors.length === 0) {
    process.exit(0);
  }

  console.error(`\nFound ${allErrors.length} broken link(s):\n`);

  const groupedByFile = {};
  for (const error of allErrors) {
    if (!groupedByFile[error.file]) {
      groupedByFile[error.file] = [];
    }
    groupedByFile[error.file].push(error);
  }

  for (const file of Object.keys(groupedByFile).sort((a, b) => a.localeCompare(b))) {
    console.error(`${file}:`);
    for (const error of groupedByFile[file]) {
      console.error(`  Line ${error.line}: [${error.link}] — ${error.reason}`);
    }
    console.error();
  }

  process.exit(1);
}

main();
