name: 'Preview Deployment'
on:
  pull_request_target:
    branches:
      - master

jobs:
  deploy:
    permissions:
      actions: read
      contents: read
      deployments: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules/
          key: node_modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build package
        id: build-package
        run: npm run build
        env:
          BASE_PATH: /
          URL: https://betaflight.com
          ORG: betaflight

      - name: Deploy to Cloudflare
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy build --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }} --branch ${{ github.head_ref }} --commit-dirty=true

      - name: Add deployment comment
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
             Preview URL: ${{ steps.deploy.outputs.deployment-url }}
          reactions: eyes, rocket
          comment-tag: 'Preview URL'
          mode: recreate
