name: Build and deploy docs
on: 
  push:
    branches:
    - 't-rex'

jobs:
  build:
    name: Build and push docs

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: NPM CI & build & deploy
      working-directory: ./docs
      run: |
        npm ci
        npm run build
        npm run deploy
